### PR TITLE
rewrite testing file

### PR DESCRIPTION
**Pull request by RichRick1**

### CODE REVIEW

**Comment by RichRick1** [comment]
I renamed the PPP.py file to MoHa.py file and created there 2 classes:
1. HamHub(inherits HamPPP) - Hubbard Hamiltonian
2. HamHuck(inherits HamHub) - Huckle Hamiltonian
Also, I rewrite tests so they are in agreement

Last but not the least, we have a draft for the [demo](https://github.com/RichRick1/ModelHamiltonian/blob/testing/upd/examples/Demonstration.ipynb).ipynb file now.
@msricher @gabrielasd @adsrichards would be glad to hear your proposals to the committed changes in general and **demo** file in particular

**Comment by gabrielasd** [comment]
I think those were good changes to the code and great job with the demo!!

Do you plan to also show the ability to save the Hamiltonians as FCIDUMP file? I see you already have some worked example for it [here](https://github.com/RichRick1/ModelHamiltonian/blob/testing/upd/examples/to_fcidump_example.py). One option could be showing how to create that file and then load it with PyCI and evaluate the energy (?)

**Comment by RichRick1** [comment]
@msricher @gabrielasd  @adsrichards I guess all issues are addressed now
Are we ready to merge this?

**Comment by adsrichards** [comment]
The demo file looks really nice to me, thanks Rik. I would say that it's good to merge.

**Pull request merged**
