### PR TITLE
created tests for hubbard chain and polyene

### PR DESCRIPTION
**Pull request by adsrichards**
Made some tests which are mostly a work in progress. Here's a description of the files:

- test_hubbard_pyscf.ipynb
FCI solution for the finite Hubbard chain with periodic boundary conditions and comparison with the infinite chain exact solution. At N=8, the solution is already quite close to the N=infinite limit.

- test_hubbard.ipynb
This is an attempt to output the integrals in FCIDUMP format for input to quantum chemistry software and obtain a solution which is consistent with the above. This still needs some work to get the FCIDUMP file into a suitable format for quantum chemistry software to accept.

- test_polyene_pyscf.ipynb
My attempt at finding the FCI solution for a more complicated system, polyene, by following this paper: [J. Chem. Phys. 108, 9246 (1998)](https://doi.org/10.1063/1.476379). This is still a work in progress as the numbers aren't quite matching up, and any help would be appreciated.

### CODE REVIEW

**Comment by PaulWAyers** [comment]
It looks to me like the interpretation of the 2nd-quantized terms is direct, so there may be the extra 1-body term.
http://dx.doi.org/10.1140/epjb/e2011-20094-1

**Comment by PaulWAyers** [comment]
Another couple possible references:
https://onlinelibrary.wiley.com/doi/10.1002/qua.10260
Also in terms of "nice" second quantization with creator/annihilators
https://www.sciencedirect.com/science/article/pii/016612809190149E?via%3Dihub

**Comment by RichRick1** [comment]
@adsrichards Thanks for a contribution. Please add symmetry and basis (spinorbital, spatial) support for generating 2 body integrals. It would be really helpful

**Comment by adsrichards** [comment]
@RichRick1 No problem, I've added those two options to the generate_two_body_integral function now.

**Pull request merged**
