### PR TITLE
Array transformation become a free function

### LINKED ISSUE #54: Array transformations should be free functions, not methods
https://github.com/theochem/ModelHamiltonian/blob/4d5d164477d02044cb113a00b948705773b64247/moha/api.py#L66

These functions, which do not use `self` or reference the parent object, should probably be free functions in `utils`, and then added to `__init__.py`.

### PR DESCRIPTION
**Pull request by Bakugo90**
FIxes #54

As suggested by PhD @msricher :

> These functions, which do not use self or reference the parent object, should probably be free functions in utils, and then added to __init__.py

I just move `to_parse` function to `utils.py` and then define it on` __init__.py` so it can be access through the package name `moha`

### CODE REVIEW

**Comment by RichRick1** [comment]
Hi @Bakugo90! Great job!
It seems like some of the style-related tests need to be fixed.

**Comment by Bakugo90** [comment]
Thank you @RichRick1 ... Some `pycodestyle errors`  I've just fixed it.

**Comment by RichRick1** [comment]
@Bakugo90 great job! I'd change one more thing: it seems like we need to exclude `docs` and `example` folders from the precommit.

**Comment by Bakugo90** [comment]
> we need to exclude docs and example folders from the precommit.

Done ! @RichRick1

**Comment by Bakugo90** [comment]
Hello mentors @RichRick1 , @PaulWAyers 

As we prepare to expand the existing package by introducing new occupation-and-spin based hamiltonian, have we compiled a list of the specific Hamiltonians to be included during this Gsoc ?

I'm currently working on outlining a timeline for implementation, and having clarity on which Hamiltonians to include and their exact quantity would greatly assist me in managing my time effectively.

**Comment by RichRick1** [comment]
@Bakugo90 Because there are implemented the most general spin-based XXZ Heisenberg hamiltonian and the most general occupation-based  Pariser-Parr-Pople hamiltonian, the general spin-based and occupation-based hamiltonian should just inherit both classes. However, it would be nice to narrow it down to t-J-U-V and t-J model.

**Comment by PaulWAyers** [comment]
@RichRick1 is this something we can close?

**Comment by RichRick1** [comment]
Yes!

**Pull request closed without merging**
