### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by msricher**
Work in progress... there are multiple definitions of the same classes.
Can you go through moha/*.py and tell me which ones to keep?

### CODE REVIEW

**Comment by adsrichards** [comment]
Someone correct me if I'm wrong, but is huckel.py not obsolete at this point? It seems like all of the functionality was rewritten/updated in the other files.

**Comment by msricher** [comment]
The code is structured as a proper Python module now:
```
[*format]-[michael@T420]-[~/Git/ModelHamiltonian]-% python
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import moha
>>> dir(moha)
['HamHub', 'HamHuck', 'HamPPP', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'api', 'hamiltonians', 'utils']
>>> 
```

I moved all IPython notebooks to `examples/`. 

There are two major things remaining:

1) Documentation strings. They should be formatted according to this standard: [NumPy doc standard](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard). Please use [PyDocStyle](http://www.pydocstyle.org/en/stable/) to check your docstrings. Also use raw triple quotes `r"""like this"""`. I need some help with this part, it's a lot...

2) Tests should go in `moha/test/test_{something}.py`, and work with [PyTest](https://docs.pytest.org/en/7.1.x/). I think @gabrielasd  offered to do this part?

Finally, I auto-formatted the code with [Black](https://github.com/psf/black), using the command `black -t py36 -l 100 *.py`. I'm not too worried about this at the moment, but eventually the code should be made to pass the [PyCodeStyle](https://pycodestyle.pycqa.org/en/latest/) checker.

@RichRick1 when you use Github Actions for deployment, the testing will use `pytest`, `pyycodestyle`, and `pydocstyle`.

Please let me know what you think!

**Comment by adsrichards** [comment]
I can definitely help out with 1. or any of the other parts when I get a chance if you need me to.

**Comment by RichRick1** [comment]
@msricher thanks a lot for the reformatting code! Everything looks great to me. Do you want me to merge it so I can fix the documentation style?

**Comment by msricher** [comment]
Sure!

**Pull request merged**
